### ISSUE TITLE
Não esta comparande strings iguais no exercício ex00 da C03

### ISSUE THREAD

**Issue by felipevencato** [eduardomosko/fake-moulinnete#8]
Eu estava olhando o código de um colega(C03/ex00) e eu tinha certeza que daria errado em uma condição em que ambas as strings era exatamente iguais, mas o código passava na fake molinette.
Ao olhar o código da fake, achei que s1 e s3 eram iguais. Demorou um tempo até eu perceber que s3 tem uma letra maiuscula.
Esta certo isso?
Se estiver, então tem que adicionar um teste para strings iguais. 

s1 = "abcdefghi";
s2 = "abcdefg";
s3 = "abcdEfghi";
s4 = "ab0defghi";

**Comment by eduardomosko** [comment]
resolvido 6bc7fe73b583a0a596eb38a7aad6b3ba55f61aa4
